function toast(msg){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2200)}
function ask(){const input=document.getElementById('question');const feed=document.getElementById('feed');if(!input||!feed||!input.value.trim())return;const u=document.createElement('div');u.className='msg user';u.textContent=input.value.trim();feed.appendChild(u);input.value='';setTimeout(()=>{const a=document.createElement('div');a.className='msg';a.innerHTML='<strong>I can map that pathway.</strong><br>Next I would check the property, council map sources, relevant planning provisions, likely consent triggers and whether a planner or another specialist should review it. <a href="platform-v5.html" style="color:#cabaff;text-decoration:underline">Open the v5 assessment workspace →</a>';feed.appendChild(a)},350)}
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&document.activeElement?.id==='question'){e.preventDefault();ask()}})
function toggleScenario(el){document.querySelectorAll('.scenario').forEach(s=>s.classList.remove('recommended'));el.classList.add('recommended');toast('Scenario selected for comparison')}
const homeCues=['Can I subdivide this section?','Can I build a second dwelling?','Can I add a deck?','Can I turn my garage into a dwelling?','What can I build on this property?','Can I build three townhouses here?'];let homeCue=0;setInterval(()=>{const i=document.getElementById('question');if(i&&document.activeElement!==i&&!i.value){homeCue=(homeCue+1)%homeCues.length;i.placeholder=homeCues[homeCue]}},2300);

function injectVerificationPanel(){
  const property=document.getElementById('property');
  const resultGrid=document.querySelector('#property .result-grid');
  if(!property||!resultGrid||document.getElementById('sourceVerification'))return;
  const style=document.createElement('style');
  style.textContent=`
  .verify-card{margin-top:16px;padding:22px}.verify-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:14px}.verify-head h3{margin:3px 0 7px;font-family:"Space Grotesk";font-size:23px}.verify-head p{margin:0;color:var(--muted);font-size:13px;line-height:1.6;max-width:760px}.verify-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.verify-row{display:grid;grid-template-columns:28px 1fr auto;gap:10px;align-items:center;padding:12px 13px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.022)}.verify-icon{width:28px;height:28px;border-radius:9px;display:grid;place-items:center;font-size:12px;font-weight:900}.verify-icon.wait{background:rgba(255,255,255,.06);color:#9ca5b0}.verify-icon.live{background:rgba(139,92,246,.18);color:#d8ccff}.verify-icon.warn{background:rgba(240,201,112,.12);color:#f0c970}.verify-icon.demo{background:rgba(255,113,133,.10);color:#ff91a1}.verify-row strong{display:block;font-size:13px}.verify-row small{display:block;color:var(--muted);font-size:10px;margin-top:3px;line-height:1.45}.verify-status{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.05em;color:#a9b2bd;text-align:right}.verify-status.live{color:#c8b7ff}.verify-status.warn{color:#f0c970}.verify-status.demo{color:#ff91a1}.verify-foot{display:flex;justify-content:space-between;gap:14px;align-items:center;margin-top:13px;padding-top:13px;border-top:1px solid var(--line)}.verify-foot p{margin:0;color:#7f8995;font-size:10px;line-height:1.55}.verify-links{display:flex;gap:7px;flex-wrap:wrap}.verify-link{padding:7px 9px;border-radius:10px;border:1px solid var(--line);font-size:10px;color:#cbbcff;background:rgba(139,92,246,.05)}.verify-link:hover{border-color:rgba(167,139,250,.35)}@media(max-width:780px){.verify-grid{grid-template-columns:1fr}.verify-head,.verify-foot{display:block}.verify-links{margin-top:10px}}`;
  document.head.appendChild(style);
  const card=document.createElement('div');
  card.id='sourceVerification';card.className='glass verify-card';
  card.innerHTML=`<div class="verify-head"><div><small style="color:#858f9b;letter-spacing:.12em">SOURCE & VERIFICATION</small><h3>What Pathway checked for this property</h3><p>Spatial council data and statutory planning verification are kept separate. Live map data can identify where to look; final planning advice still needs the current plan provisions and professional judgement.</p></div><span id="verifyOverall" class="pill silver">Waiting for property</span></div><div class="verify-grid">
  <div class="verify-row" data-v="address"><span class="verify-icon wait">•</span><div><strong>Council property / address data</strong><small>Auckland Council public ArcGIS address service.</small></div><span class="verify-status">Waiting</span></div>
  <div class="verify-row" data-v="zone"><span class="verify-icon wait">•</span><div><strong>Auckland Unitary Plan zone</strong><small>Spatial zoning layer for the selected point.</small></div><span class="verify-status">Waiting</span></div>
  <div class="verify-row" data-v="precinct"><span class="verify-icon wait">•</span><div><strong>Precinct layer</strong><small>Checked against the council precinct spatial layer.</small></div><span class="verify-status">Waiting</span></div>
  <div class="verify-row" data-v="overlays"><span class="verify-icon wait">•</span><div><strong>Priority overlays checked</strong><small>Includes SEA, special character, airport/noise and national-grid checks in this prototype.</small></div><span class="verify-status">Waiting</span></div>
  <div class="verify-row" data-v="controls"><span class="verify-icon wait">•</span><div><strong>Priority controls checked</strong><small>Includes coastal inundation, stormwater and subdivision controls in this prototype.</small></div><span class="verify-status">Waiting</span></div>
  <div class="verify-row" data-v="designation"><span class="verify-icon wait">•</span><div><strong>Designations checked</strong><small>Selected point checked against the council designation layer.</small></div><span class="verify-status">Waiting</span></div>
  <div class="verify-row" data-v="statutory"><span class="verify-icon warn">!</span><div><strong>Current statutory provisions</strong><small>Zone/overlay findings must be read with the operative AUP text, objectives, policies and rules.</small></div><span class="verify-status warn">Review required</span></div>
  <div class="verify-row" data-v="changes"><span class="verify-icon warn">!</span><div><strong>Plan changes / appeals / updates</strong><small>Not yet fully automated in this prototype. Must be checked before final advice.</small></div><span class="verify-status warn">Manual check</span></div>
  </div><div class="verify-foot"><p id="verifyRetrieved">No property search completed yet.</p><div class="verify-links"><a class="verify-link" href="https://geomapspublic.aucklandcouncil.govt.nz/viewer/index.html" target="_blank" rel="noopener">Council GeoMaps ↗</a><a class="verify-link" href="https://unitaryplan.aucklandcouncil.govt.nz/" target="_blank" rel="noopener">Auckland Unitary Plan ↗</a><button class="verify-link" style="cursor:pointer" onclick="showWhy('Source hierarchy','Pathway treats spatial GeoMaps/ArcGIS information as evidence of mapped planning layers, then requires the current statutory plan text and any relevant plan changes to be checked before final professional advice.')">How verification works</button></div></div>`;
  resultGrid.insertAdjacentElement('afterend',card);
  const setState=(key,state,label)=>{const r=card.querySelector(`[data-v="${key}"]`);if(!r)return;const icon=r.querySelector('.verify-icon'),status=r.querySelector('.verify-status');icon.className='verify-icon '+state;status.className='verify-status '+state;icon.textContent=state==='live'?'✓':state==='warn'?'!':state==='demo'?'×':'•';status.textContent=label};
  const refresh=()=>{
    const live=(document.getElementById('liveStatus')?.textContent||'').toLowerCase();
    const zone=(document.getElementById('zoneVal')?.textContent||'').trim();
    const precinct=(document.getElementById('precinctVal')?.textContent||'').trim();
    const overlay=(document.getElementById('overlayVal')?.textContent||'').trim();
    const retrieved=(document.getElementById('retrievedVal')?.textContent||'').trim();
    const isLive=live.includes('live auckland council')||live.includes('live council');
    const isDemo=live.includes('demo fallback')||zone.toLowerCase().includes('demo only');
    if(isDemo){['address','zone','precinct','overlays','controls','designation'].forEach(k=>setState(k,'demo','Not confirmed'));card.querySelector('#verifyOverall').textContent='Demo / unverified';card.querySelector('#verifyOverall').className='pill silver';}
    else if(isLive){setState('address','live','Live');setState('zone',zone&&zone!=='—'&&!zone.toLowerCase().includes('unavailable')?'live':'warn',zone&&zone!=='—'?'Retrieved':'Check');setState('precinct','live',precinct==='Detected'?'Detected':'Checked');setState('overlays','live','Checked');setState('controls','live','Checked');setState('designation','live','Checked');card.querySelector('#verifyOverall').textContent='Council spatial checks complete';card.querySelector('#verifyOverall').className='pill violet';}
    else{['address','zone','precinct','overlays','controls','designation'].forEach(k=>setState(k,'wait','Waiting'));card.querySelector('#verifyOverall').textContent='Waiting for property';card.querySelector('#verifyOverall').className='pill silver';}
    const text=retrieved&&retrieved!=='—'?`Council spatial data retrieved ${retrieved}. Statutory AUP text and current plan changes remain separate verification steps.`:'No property search completed yet.';card.querySelector('#verifyRetrieved').textContent=text;
  };
  ['liveStatus','zoneVal','precinctVal','overlayVal','retrievedVal','recordTitle'].forEach(id=>{const el=document.getElementById(id);if(el)new MutationObserver(refresh).observe(el,{childList:true,subtree:true,characterData:true})});
  refresh();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',injectVerificationPanel);else injectVerificationPanel();
